export const Address = {
  GOVERNANCE_CONTROLLER_ADDRESS: import.meta.env
    .VITE_GOVERNANCE_CONTROLLER_ADDRESS,
  ICGOV_TOKEN_ADDRESS: import.meta.env.VITE_ICGOV_TOKEN_ADDRESS,
  GOVERNANCE_CONTRACT_ADDRESS: import.meta.env.VITE_GOVERNANCE_CONTRACT_ADDRESS,
  IC_TOKEN_ADDRESS: import.meta.env.VITE_IC_TOKEN_ADDRESS,
  ICBTC_TOKEN_ADDRESS: import.meta.env.VITE_ICBTC_TOKEN_ADDRESS,
  ICAUT_TOKEN_ADDRESS: import.meta.env.VITE_ICAUT_TOKEN_ADDRESS,
  IC_CONTROLLER: import.meta.env.VITE_IC_CONTROLLER_ADDRESS,
  VAULT_AND_YIELD_ADDRESS: import.meta.env.VITE_VAULT_AND_YIELD_ADDRESS,
  MOCK_ORACLE_ADDRESS: import.meta.env.VITE_MOCK_ORACLE_ADDRESS,
};
